# Generated by Django 4.1.5 on 2023-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_alter_connected_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('agent', 'agent'), ('customer', 'customer')], max_length=50, null=True),
        ),
    ]
